### GAME CLIENT GET
GET https://thuongvachon.herokuapp.com/api/games/clientGet

### CREATE COLLECTION
GET http://localhost:8080/home/createCollection

### ADMIN GAME GET
GET http://localhost:8080/api/games/adminGet


### NOTE GET
GET http://localhost:8080/api/todos/get

### NOTE ADD
POST http://localhost:8080/api/todos/add
Content-Type: application/json

{
    "data":"haha"
}

### NOTE DELETE MANY
DELETE http://localhost:8080/api/todos/delete
Content-Type: application/json

{
    "data":"haha"
}

### Create a doc

POST http://localhost:8080/api/docs/create
Content-Type: application/json

{
    "data":{
        "type":"Nodejs new 3",
        "content":"This is the nodejs new 3 content",
        "title":"Nodejs new 3 title" 
    }
}

### get doc Content

GET http://localhost:8080/api/docs/getContent
Content-Type: application/json

{
    "data":"615ec6fe6249d37fc116bace"
}

### Register 
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "data":{
        "fullname":"Tran Thi Diem Thuong",
        "username":"tdtthuong",
        "password":"Kelkifa123"
    }
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "data":{
        "username":"huan",
        "password":"Kelkifa123"
    }
}


############ TEST ####################
POST http://localhost:8080/api/docs/createGroup
Content-Type: application/json

{
    "name":"Thuong va Chon",
    "usernames":["huan"]
}

### Get group
GET http://localhost:8080/api/groups/get
Content-Type: application/json

{
    "userId":"617c0f43e97f8ab22b12e4asa4"
}

### Create doc userId :thuong
POST http://localhost:8080/api/docs/createDoc
Content-Type: application/json

{
    "name":"CSS",
    "userId":"617c0f43e97f8ab22b12e4a4",
    "title": "Padding",
    "content": "Padding",
    "groupId": "617d5b1b9aec4e5642da1d92"
}

### Get doc name list

GET http://localhost:8080/api/docs/getDoc
Content-Type: application/json

{
    "userId": "",
    "groupId": "617d500cd146d3699a5ce899"
}


### Get doc detail
GET http://localhost:8080/api/docs/getDocDetail

Content-Type: application/json

{
    "userId": "617c0f10e97f8ab22b12e4a1",
    "groupId": "617d5b1b9aec4e5642da1d92",
    "docId":"617d5c239aec4e5642da1d97"
}


### doc create content
POST http://localhost:8080/api/docs/createContent
Content-Type: application/json

{
    "userId":"617c0f10e97f8ab22b12e4a1",
    "groupId":"6185432d4db393e45c580824",
    "docId":"618548384510160c74ac1e5d",
    "title":"iu mài 3",
    "content":"noi dung iu mai 2"
}


### delete contents

PATcH http://localhost:8080/api/docs/deleteContent
Content-type: application/json

{
    "userId":"617c0f10e97f8ab22b12e4a1",
    "docId":"61873be376dc25efbe99173f",
    "contentId":"61873e2f9f2794ec76791384"
}


### todos

POST http://localhost:8080/api/todos/get
Content-Type: application/json

{
    "userId": "6176b75b9ba1c3309bdcfd14",
    "groupId": "6185432d4db393e45c580824"
}
### todo change state
POST http://localhost:8080/api/todos/changeState
Content-Type: application/json

{
    "userId": "6176b75b9ba1c3309bdcfd14",
    "noteId":"61d022692d321405d3b07f4c",
    "todoId":"61d11f936dd255b274730f41",
    "state":"true",
    "groupId":"6185432d4db393e45c580824"
}


###
POST http://localhost:8080/api/todos/addTodo
Content-Type: application/json

{
    "userId": "6176b75b9ba1c3309bdcfd14",
    "groupId": "6185432d4db393e45c580824",
    "todoName":"new todo",
    "todoId":"61d022692d321405d3b07f4c"
}


### change home
GET http://localhost:8080/change


### always change

POST http://localhost:8080/api/docs/alwaysChange
Content-Type: application/json

{
    "docId":"618548384510160c74ac1e5d"
}


