### GAME CLIENT GET
GET https://thuongvachon.herokuapp.com/api/games/clientGet

### CREATE COLLECTION
GET http://localhost:8080/home/createCollection

### ADMIN GAME GET
GET http://localhost:8080/api/games/adminGet


### NOTE GET
GET http://localhost:8080/api/todos/get

### NOTE ADD
POST http://localhost:8080/api/todos/add
Content-Type: application/json

{
    "data":"haha"
}

### NOTE DELETE MANY
DELETE http://localhost:8080/api/todos/delete
Content-Type: application/json

{
    "data":"haha"
}

### Create a doc

POST http://localhost:8080/api/docs/create
Content-Type: application/json

{
    "data":{
        "type":"Nodejs new 3",
        "content":"This is the nodejs new 3 content",
        "title":"Nodejs new 3 title" 
    }
}

### get doc Content

GET http://localhost:8080/api/docs/getContent
Content-Type: application/json

{
    "data":"615ec6fe6249d37fc116bace"
}

### Register 
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "data":{
        "fullname":"Tran Thi Diem Thuong",
        "username":"tdtthuong",
        "password":"Kelkifa123"
    }
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "data":{
        "username":"huan",
        "password":"Kelkifa123"
    }
}


############ TEST ####################
POST http://localhost:8080/api/docs/createGroup
Content-Type: application/json

{
    "name":"Group 1",
    "usernames":["huan", "tdtthuong"]
}

### Get group
GET http://localhost:8080/api/docs/getGroup